# Generated by Django 6.0.6 on 2026-06-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
