# Generated by Django 6.0.6 on 2026-06-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ai_solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
