# Generated by Django 6.0.6 on 2026-06-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='verification_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
